CanalTP/asgard

asgard/asgard.cpp, asgard/projector.h
With lots of cleanups and fixes
=> Use valhalla.json as configuration to be iso valhalla

Dockerfile, asgard/asgard.cpp
Fix #6 
Need an update of the ci docker image for the ci to pass.
=> update to latest version of valhalla

asgard/asgard.cpp, asgard/projector.h
From home to work, after warming.
| modes | new_default | kraken | valhalla | asgard | asgard with cache=0 |
|---------- |----------------:|----------:|----------:|----------:|----------------------------:|
|w+w     | 320ms | 370ms | 900ms | 370ms | 480ms |
|wbc+w | 1000ms | 1670ms | 2200ms | 800ms | 1500ms |
=> Projection cache by mode + stop when limit is reached

.travis.yml, CMakeLists.txt, asgard/CMakeLists.txt, asgard/asgard.cpp, asgard/context.h, asgard/direct_path_response_builder.cpp, asgard/direct_path_response_builder.h, asgard/handler.cpp, asgard/handler.h, asgard/projector.h, asgard/tests/CMakeLists.txt, asgard/tests/direct_path_response_builder_test.cpp, asgard/util.cpp, asgard/util.h, cmake_modules/UseBoost.cmake
=> Asgard direct path

.gitmodules, .travis.yml, CMakeLists.txt, asgard/CMakeLists.txt, asgard/asgard.cpp, asgard/context.h, asgard/handler.cpp, asgard/handler.h, asgard/metrics.cpp, asgard/metrics.h, cmake_modules/ThirdParty.cmake
https://jira.kisio.org/browse/NAVP-1164
=> Installing Prometheus metrics

asgard/handler.cpp
https://jira.kisio.org/browse/NAVITIAII-2829
=> Handle projection errors

CMakeLists.txt, cmake_modules/FindValhalla.cmake
I didn't want to install valhalla on /usr so I made the include_dir configurable
=> allow to use custom installation of valhalla

docker/asgard-app/Dockerfile, docker/asgard-data/Dockerfile
We couldn't launch asgard-query... Fixed it!
=> fix asgard query permission

asgard/metrics.cpp, asgard/metrics.h
I tried https://github.com/include-what-you-use/include-what-you-use.
It detects some cycle in boost and doesn't want to work further... It manages to give us some advice though. I just applied it.
=> Trying iwyu

asgard/CMakeLists.txt, asgard/asgard.cpp
=> log zmq exception

docker/asgard-data/Dockerfile
=> add elevation data

asgard/direct_path_response_builder.cpp, asgard/direct_path_response_builder.h, asgard/handler.cpp, asgard/tests/direct_path_response_builder_test.cpp, asgard/tests/handler_test.cpp
- First, a few minor changes to handler.cpp
- Added maneuvers instructions, direction (turn degrees), duration and length to Asgard
- Added/edited tests
_Please note that we will then need to do a little translation from coord to adress name in the arrival instruction, as seen on this screenshot._
=> Maneuvers instructions in Asgard

JenkinsfileBuildAppImage, JenkinsfileBuildDataImage
=> [Jenkins] move remove useless images

README.md
Just few words to explain the Asgard launching.
=> [doc] enrich doc

.jenkins/JenkinsfileBuildAppImage, .jenkins/JenkinsfileBuildDataImage, .jenkins/JenkinsfileBuildDepsImage, Makefile
Remove navitia/asgard-build-deps:latest before building
=> remove build-deps before building docker

.jenkins/JenkinsfileBuildAppImage, .jenkins/JenkinsfileBuildDataImage, .jenkins/JenkinsfileBuildDepsImage
schema :
```
Push on master or release -> trig deps build and push   |---> trig data build and push
|---> trig app build and push
```
I tested by hand and it works !
=> Jenkins: pipe in sequential mode

asgard/direct_path_response_builder.cpp, asgard/handler.cpp
- remove some useless log
- add some specific logs
=> improve log

asgard/handler.cpp, docker/asgard-app/Dockerfile, docker/asgard-data/Dockerfile
Whenever there is an exception, we must catch it.
Valhalla throws exceptions in some very specific cases and we don't want Asgard to crash because of that...
=> catch exception

asgard/handler.cpp, asgard/handler.h
When no solution is found or an exception is thrown, the structure in Algo should be cleared...
=> Use RAII to clear

asgard/asgard.cpp, asgard/asgard_conf.h, asgard/handler.cpp, asgard/metrics.cpp, asgard/metrics.h, asgard/projector.h, asgard/tests/projector_test.cpp
=> Multi cache in Asgard

asgard/handler.cpp, asgard/tests/handler_test.cpp
We cannot travel at light speed, even tough we wish so :)
=> clamp speed and matrix distance

asgard/direct_path_response_builder.cpp, asgard/direct_path_response_builder.h, asgard/tests/direct_path_response_builder_test.cpp
=> fill name in address

asgard/CMakeLists.txt, asgard/asgard_conf.h
Hi guys!
When the valhalla configuration file does not exist, we don't have any log telling us.
This PR aims to fix that.
Navitia kiss :octopus: :car:
=> Log when the valhalla conf file is not found

docker/asgard-data/Dockerfile
With this PR, we are able to handle multiple pbfs of different regions...
=> make docker-data multi pbf

asgard/handler.cpp, asgard/tests/handler_test.cpp
=> fix missing mode bss

.github/workflows/docker_valhalla.yml, docker/asgard-build-deps/Dockerfile, docker/asgard-valhalla-service/Dockerfile, docker/valhalla-build/Dockerfile, docker/valhalla-run/Dockerfile
This manual workflow allow to generate valhalla dockers images needed by asgard 
Input of this workflow : 
- Valhalla dockers tag (ex 3.1.4 or latest) 
- Valhalla branch tag (navitia/valhalla fork, ex 3.1.4 or any custom tag)
=> Workflow dispatch for valhalla docker generation

asgard/direct_path_response_builder.cpp
=> Fix Poi name in proto response

asgard/direct_path_response_builder.cpp, asgard/direct_path_response_builder.h, asgard/tests/direct_path_response_builder_test.cpp
[JIRA ticket](https://navitia.atlassian.net/browse/NAV-982)
[Specs](https://navitia.atlassian.net/wiki/spaces/NAV/pages/11943051622/Interfaces+routi+res)
=> Add street_information for bike
